services:

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db:/data/db

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PORT: $API_PORT
      DATABASE_URL: $DATABASE_URL
    ports:
      - $API_PORT:$API_PORT
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - postgres

volumes:
  db: